name: Monthly SP500 EPS Download

on:
  schedule:
    # Run on the 4th day of every month at 00:00 UTC
    - cron: "0 0 4 * *"
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  download_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install requests

    - name: Run the script
      run: python scripts/download_sp500_eps.py
