name: Excel - Household Debt Service

on:
  schedule:
    - cron: '5 2 2 2,5,8,11 *'  # Runs at 02:05 UTC on the 2nd day of Feb, May, Aug, Nov
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write

jobs:
  update_excel:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests beautifulsoup4

      # Run the Python script
      - name: Run update script
        run: python scripts/excel-household-debt-service.py

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated update of Household Debt Service Excel file" || echo "No changes to commit"
          git push
