name: Excel - Labor Force Participation

on:
  schedule:
    - cron: "10 7 11 4 *"  # Runs at 07:10 UTC on April 11 every year
  workflow_dispatch:  # Allows manual triggering if needed

permissions:
  contents: write

jobs:
  update_excel:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests openpyxl pandas

      # Run the Python script
      - name: Run update script
        run: python scripts/excel-labor-participation.py

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Automated update of Excel file"
          git push
