name: 7.2 Pages - AI

on:
  schedule:
    - cron: "10 4 12 * *"  # Run on the 12th day of every month at 04:10 AM UTC
  workflow_dispatch:  # Allows manual triggering if needed

permissions:
  contents: write

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas openpyxl

      - name: Run Python script
        run: python scripts/pages-ai.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add ./ai/index.html
          git commit -m "Updated HTML with latest data"
          git push
