name: Update S&P 500 Price

on:
  schedule:
    - cron: "0 22 * * *"  # Runs daily at 5 PM Montreal time (adjust for UTC)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_price:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install schedule requests beautifulsoup4 openpyxl

      - name: Run the script
        run: python scripts/update_sp500_price.py
